using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using ToBOE.Dialogue.Importer.CodeGen;

namespace ToBOE.Dialogue.Importer
{
    public class DialogueImportWindow : EditorWindow
    {
        TextAsset tsvFile;
        bool generateCharactersEnum;
        bool generateStatusEnum;
        bool generateIDEnum = true;

        [MenuItem("Dialogue/Import Window")]
        public static void ShowWindow()
        {
            DialogueImportWindow window = EditorWindow.GetWindow<DialogueImportWindow>();
            window.titleContent = new GUIContent("Import Dialogue");
            window.minSize = new Vector2(300, 400);
        }

        private void OnGUI()
        {
            tsvFile = EditorGUILayout.ObjectField("Lines File", tsvFile, typeof(TextAsset), false) as TextAsset;
            generateCharactersEnum = EditorGUILayout.Toggle("Generate Characters Enum", generateCharactersEnum);
            generateStatusEnum = EditorGUILayout.Toggle("Generate Status Enum", generateStatusEnum);
            generateIDEnum = EditorGUILayout.Toggle("Generate LineID Enum", generateIDEnum);
            if (GUILayout.Button("Save Test Enum"))
            {
                CodeFile cf = new CodeFile("TestEnum.cs", "Scripts/Dialogue System/Autogenerated");
                cf.AddUsingDirective("System");
                cf.AddAutoGeneratedPreamble();
                cf.Space();
                cf.AddComment("Little test!");

                using (cf.Namespace("ToBOE.Dialogue"))
                {
                    cf.AddComment("Test enum");
                    using (cf.Enum(CodeFile.Modifiers.Public, "TestEnum", "short"))
                    {
                        cf.EnumValue("TestValue1");
                        cf.EnumValue("Beaut", 5);
                        cf.EnumValue("IdkNum3");
                    }
                }

                cf.SaveToDisk();
            }
        }
    }
}
