using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using static System.IO.Path;

namespace BeyondTheDoor
{
    public static class FilePaths
    {
        public static readonly string Assets = Application.dataPath;
        public static readonly string Scripts = Combine(Assets, "Scripts");
        public static readonly string Lines = Combine(Assets, "Lines");
        public static readonly string DialogueSystem = Combine(Scripts, "Core");
        public static readonly string Autogenerated = Combine(DialogueSystem, "Autogenerated");

        public static readonly string ConversationsFolderName = "Conversations";
        public static readonly string Conversations = Combine(Assets, ConversationsFolderName);

        /// <summary>
        /// Use this for System.IO functions.
        /// </summary>
        /// <param name="day"></param>
        /// <returns></returns>
        public static string GetConversationsFolderForDay(int day)
        {
            if (day == -1)
                return Conversations;
            return Combine(Conversations, "Day " + day);
        }

        /// <summary>
        /// Use this for AssetDatabase functions.
        /// </summary>
        /// <param name="day"></param>
        /// <returns></returns>
        public static string GetRelativeConversationsFolderForDay(int day)
        {
            if (day == -1)
                return ConversationsFolderName;
            return Combine(ConversationsFolderName, "Day " + day);
        }

        //public static readonly string CharacterEnumFileName = "Character.cs";
        //public static readonly string LineIDEnumFileName = "LineID.cs";
        //public static readonly string LineStatusEnumFileName = "LineStatus.cs";

        public static readonly string DialogueNamespace = "BeyondTheDoor";

        public static readonly string ExcelLinesFileName = "ExcelLines.txt";
        public static readonly string ExcelLinesFilePath = Combine(Application.dataPath, ExcelLinesFileName);

        public static bool ExcelFileExists => System.IO.File.Exists(ExcelLinesFilePath);
    }
}
