// =================================================
// =                                               =
// = Character.Autogenerated.cs                    =
// =                                               =
// = AUTO-GENERATED FILE - Do not edit!            =
// =                                               =
// =================================================

using System.Collections.Generic;

namespace ToBOE.Dialogue
{
    public partial class Character
    {
        public static Character Bob { get; private set; } = new Character(CharacterID.Bob);
        public static Character Player { get; private set; } = new Character(CharacterID.Player);
        public static Character Jessica { get; private set; } = new Character(CharacterID.Jessica);

        /// <summary>
        /// All characters in the game.
        /// <summary>
        public static Dictionary<CharacterID, Character> All { get; private set; } = new Dictionary<CharacterID, Character>()
        {
            { CharacterID.Bob, Bob },
            { CharacterID.Player, Player },
            { CharacterID.Jessica, Jessica },
        };
    }
}

