// =================================================
// =                                               =
// = Line.Autogenerated.cs                         =
// =                                               =
// = AUTO-GENERATED FILE - Do not edit!            =
// =                                               =
// =================================================

namespace ToBOE.Dialogue
{
    public partial class Line
    {
        public static Line test1_line1 { get; private set; } = new Line(Character.TestActor1, "This is the first line", "idk lol", 1, LineID.test1_line1, LineStatus.Placeholder, VoiceStatus.None, "brrrt");
        public static Line test1_line2 { get; private set; } = new Line(Character.TestActor1, "Noice (2nd line)", "mmmmm", 1, LineID.test1_line2, LineStatus.Draft, VoiceStatus.None, "zazaza");
        public static Line test2_line1 { get; private set; } = new Line(Character.TestActor2, "Actor 2 line", "yada", 1, LineID.test2_line1, LineStatus.Final, VoiceStatus.None, "yoink");
    }
}

